#!/bin/bash
set -e

KERNEL_VERSION=$(uname -r)
MODULES_DIR="/lib/modules/${KERNEL_VERSION}"

WORKDIR=$(mktemp -d)
REQ_KO="$WORKDIR/required-ko.txt"
REQ_KOXZ="$WORKDIR/required-koxz.txt"
REQ_ALL="$WORKDIR/required-firmware.txt"
AVAIL="$WORKDIR/available-firmware.txt"
MISSING="$WORKDIR/missing-firmware.txt"

echo "[*] Scanning uncompressed modules..."
find "$MODULES_DIR" -type f -name '*.ko' | while read -r module; do
    modinfo "$module" 2>/dev/null | awk -F':' '/^firmware:/ { print $2 }' | sed 's/^[ \t]*//' || true
done | sort -u > "$REQ_KO"

echo "[*] Scanning compressed modules (.ko.xz)..."
find "$MODULES_DIR" -type f -name '*.ko.xz' | while read -r mod_xz; do
    tmp=$(mktemp --suffix=.ko)
    xz -dc "$mod_xz" > "$tmp"
    modinfo "$tmp" 2>/dev/null | awk -F':' '/^firmware:/ { print $2 }' | sed 's/^[ \t]*//' || true
    rm -f "$tmp"
done | sort -u > "$REQ_KOXZ"

cat "$REQ_KO" "$REQ_KOXZ" | sort -u > "$REQ_ALL"

echo "[*] Indexing installed firmware..."
find /lib/firmware -type f | sed 's|/lib/firmware/||' | sort -u > "$AVAIL"

echo "# Missing firmware blobs required by kernel modules (generated by check-firmware.sh)" > "$MISSING"
echo "# Add entries below to firmware-list.txt if inclusion in the Volumio build is desired." >> "$MISSING"
comm -23 "$REQ_ALL" "$AVAIL" >> "$MISSING"

echo "[+] Missing firmware list:"
cat "$MISSING"

echo ""
echo "[+] Saved:"
echo "    All required: $REQ_ALL"
echo "    Available:    $AVAIL"
echo "    Missing:      $MISSING"
